### PR TITLE
Update `k8s.io/legacy-cloud-providers` to `v1.25.2`

### PR DESCRIPTION
**Pull request by shafeeqes**
**What this PR does / why we need it**:
Update `k8s.io/legacy-cloud-providers` to `v1.25.2`

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/6567

**Special notes for your reviewer**:

**Release note**:

```feature dependency
`k8s.io/legacy-cloud-providers` is now updated to `v1.25.2`.
```

### CODE REVIEW

**Comment by ghost** [comment]
@shafeeqes Command `/cherrypick` is not known.

**Review by ialidzhikov — COMMENTED** [review]
Shouldn't this PR actually be created against the `release-v1.25` branch?

**Comment by shafeeqes** [comment]
I thought I'll update the `legacy-cloud-provider` branch as well, I will cherry-pick this PR once it's merged.

**Review by rfranzke — APPROVED** [review]

**Pull request merged**
